### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by ziraiken** [Jerenaux/phaserquest#14] opened 2019-04-14 17:00 UTC
Listening on 8081
/root/phaserquest/js/server/GameServer.js:686
    GameServer.dirtyAOIs.forEach(function(aoi){
                         ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.GameServer.clearAOIs (/root/phaserquest/js/server/GameServer.js:686:26)
    at Timeout.GameServer.updatePlayers [as _onTimeout] (/root/phaserquest/js/server/GameServer.js:679:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

How to fix that?

**Comment by Jerenaux** [comment] 2019-04-14 18:18
This error should normally never happen, can you provide information to reproduce it? In what context did you run the game? Are there other errors in the log before that one?

**Comment by Jerenaux** [comment] 2019-08-06 16:55
Closing due to lack of follow up.

**Closed as completed by Jerenaux** 2019-08-06 16:55 UTC
